#!/usr/bin/env python3
"""Regenerate the FLEET_MACHINES / PORTABLE_EQUIPMENT arrays embedded in index.html
from the price workbook (data/Fleet_Rental_Prices_2026.xlsx).

Stdlib only — no openpyxl required. Dry-run by default; pass --write to save.

Rate model per fleet unit (Rs., excl. VAT):
                 Hourly                Daily (4h basis)            Per-KM
  fw FULLY WET   Excel "Hourly WET"    Excel "Daily WET (4h)"      legacy pkw
  w  WET         min(round50(dry       min(round50(dailyDry        round5(pkd +
     (driver,      + op*1.2), fw)        + op*4*1.2), fw)            (pkw-pkd)*op/(fuel+op))
      no fuel)
  d  DRY         Excel "Hourly DRY"    Excel "Daily DRY (4h)"      legacy pkd

fuel/op come from the "Engineering Cost" sheet joined by E&C No.; units without a
match fall back to the category mean, then the global mean, and are flagged est:1.
Per-km rates exist only in the HTML's legacy array (210 transport units) and are
preserved positionally (asserted against reg + E&C No. per index).
"""

import argparse
import json
import math
import re
import sys
import xml.etree.ElementTree as ET
import zipfile
from collections import defaultdict

NS_MAIN = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
NS_REL = "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}"

BEGIN_MARK = "/* ==FLEET-DATA:BEGIN== generated by tools/build_fleet_data.py — do not edit by hand */"
END_MARK = "/* ==FLEET-DATA:END== */"

# Catalogue items hired out but not present in the Excel "Portable Equipment
# Rates" sheet — appended after the sheet items on every build. Day rates in
# Rs.: dw = WET (incl. fuel & operator), dd = DRY (bare hire), VAT excluded.
EXTRA_PORTABLE = [
    {"cat": "Light Plant", "cap": "4×400 W LED tower (mobile, diesel)", "dw": 9500, "dd": 6000},
    {"cat": "Light Plant", "cap": "4×1000 W metal-halide tower (diesel)", "dw": 12500, "dd": 8000},
    {"cat": "Concrete Mixer", "cap": "5/3.5 cu.ft (petrol, half-bag)", "dw": 3000, "dd": 2000},
    {"cat": "Concrete Mixer", "cap": "10/7 cu.ft drum (diesel, one-bag)", "dw": 4500, "dd": 3000},
    {"cat": "Concrete Mixer", "cap": "10/7 cu.ft with hopper / hoist", "dw": 6500, "dd": 4500},
]


def round_step(x, step):
    # JS Math.round semantics (half away from zero for positives), not banker's
    return int(math.floor(x / step + 0.5)) * step


def col_letter(ref):
    return re.match(r"[A-Z]+", ref).group()


class Workbook:
    def __init__(self, path):
        self.zf = zipfile.ZipFile(path)
        self.shared = self._shared_strings()
        self.sheets = self._sheet_map()

    def _shared_strings(self):
        try:
            root = ET.fromstring(self.zf.read("xl/sharedStrings.xml"))
        except KeyError:
            return []
        out = []
        for si in root.findall(f"{NS_MAIN}si"):
            out.append("".join(t.text or "" for t in si.iter(f"{NS_MAIN}t")))
        return out

    def _sheet_map(self):
        wb = ET.fromstring(self.zf.read("xl/workbook.xml"))
        rels = ET.fromstring(self.zf.read("xl/_rels/workbook.xml.rels"))
        relmap = {r.get("Id"): r.get("Target") for r in rels}
        sheets = {}
        for s in wb.find(f"{NS_MAIN}sheets"):
            target = relmap[s.get(f"{NS_REL}id")]
            if not target.startswith("xl/"):
                target = "xl/" + target.lstrip("/")
            sheets[s.get("name")] = target
        return sheets

    def rows(self, sheet_name):
        """Yield (row_number, {col_letter: value}) with shared strings resolved."""
        root = ET.fromstring(self.zf.read(self.sheets[sheet_name]))
        for row in root.iter(f"{NS_MAIN}row"):
            cells = {}
            for c in row:
                ref = c.get("r")
                if not ref:
                    continue
                v = c.find(f"{NS_MAIN}v")
                if v is None or v.text is None:
                    continue
                val = v.text
                if c.get("t") == "s":
                    val = self.shared[int(val)]
                cells[col_letter(ref)] = val
            yield int(row.get("r")), cells


def num(val):
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


def parse_fleet_pricing(wb):
    """Data rows of the Fleet Pricing sheet (skip title/header/category banners)."""
    units = []
    for r, c in wb.rows("Fleet Pricing"):
        if r < 5:
            continue
        hw, hd, dyw, dyd = (num(c.get(k)) for k in ("H", "I", "J", "K"))
        if hw is None or c.get("B") is None:
            continue  # category banner or blank row
        units.append({
            "cat": c.get("B", "").strip(),
            "brand": (c.get("C") or "").strip(),
            "ec": (c.get("D") or "").strip(),
            "model": (c.get("E") or "").strip(),
            "year": (c.get("F") or "").strip(),
            "reg": (c.get("G") or "").strip(),
            "hw": hw, "hd": hd, "dyw": dyw, "dyd": dyd,
        })
    return units


def parse_engineering(wb):
    """E&C No. -> (fuel/h, operator/h), plus category means and global mean."""
    by_ec, by_cat = {}, defaultdict(list)
    for r, c in wb.rows("Engineering Cost"):
        if r < 5:
            continue
        fuel, op = num(c.get("H")), num(c.get("I"))
        ec = (c.get("D") or "").strip()
        cat = (c.get("B") or "").strip()
        if fuel is None or op is None or not ec:
            continue
        by_ec[ec] = (fuel, op)
        if cat:
            by_cat[cat].append((fuel, op))
    cat_mean = {k: (sum(f for f, _ in v) / len(v), sum(o for _, o in v) / len(v))
                for k, v in by_cat.items() if v}
    allv = list(by_ec.values())
    global_mean = (sum(f for f, _ in allv) / len(allv), sum(o for _, o in allv) / len(allv))
    return by_ec, cat_mean, global_mean


def parse_portable(wb):
    items = []
    for r, c in wb.rows("Portable Equipment Rates"):
        if r < 5:
            continue
        dw, dd = num(c.get("D")), num(c.get("E"))
        if dw is None or not c.get("B"):
            continue
        cat, cap = c.get("B", "").strip(), (c.get("C") or "").strip()
        items.append({
            "id": 600 + len(items),
            "cat": cat,
            "cap": cap,
            "label": f"{cat} · {cap}",
            "dw": int(dw), "dd": int(dd),
        })
    for x in EXTRA_PORTABLE:
        items.append({
            "id": 600 + len(items),
            "cat": x["cat"],
            "cap": x["cap"],
            "label": f"{x['cat']} · {x['cap']}",
            "dw": int(x["dw"]), "dd": int(x["dd"]),
        })
    return items


def harvest_legacy(html):
    """Pull the existing FLEET_MACHINES array (any prior format) out of index.html."""
    m = re.search(r"const FLEET_MACHINES = (\[.*?\]);", html, re.S)
    if not m:
        sys.exit("ERROR: could not find `const FLEET_MACHINES = [...]` in index.html")
    return json.loads(m.group(1).replace("<\\/", "</"))


def build_fleet(excel_units, legacy, eng_by_ec, cat_mean, global_mean, report):
    if len(excel_units) != len(legacy):
        sys.exit(f"ERROR: Excel has {len(excel_units)} units but HTML array has {len(legacy)} — "
                 "row alignment broken; refusing to merge positionally.")
    fleet = []
    for i, (xu, lg) in enumerate(zip(excel_units, legacy)):
        # positional merge sanity check — reg and E&C No. must agree
        if (xu["reg"] or "") != (lg.get("reg") or "") or (xu["ec"] or "") != (lg.get("ec") or ""):
            report["mismatches"].append(
                f"  row {i}: excel reg/ec = {xu['reg']!r}/{xu['ec']!r} "
                f"vs html {lg.get('reg')!r}/{lg.get('ec')!r}")
            continue

        est = 0
        pair = eng_by_ec.get(xu["ec"])
        if pair is None:
            pair = cat_mean.get(xu["cat"])
            est = 1
            if pair is None:
                pair = global_mean
                report["global_fallback"].append(f"{xu['ec'] or '(no ec)'} {xu['cat']}")
            else:
                report["cat_fallback"].append(f"{xu['ec'] or '(no ec)'} {xu['cat']}")
        fuel, op = pair

        hw, hd = xu["hw"], xu["hd"]
        dyw, dyd = xu["dyw"], xu["dyd"]

        # clamp into [dry, fully wet] — rounding can dip below dry when op ≈ 0,
        # and operator-dominated cheap transport can exceed fully wet
        h_w = round_step(hd + op * 1.2, 50)
        if h_w > hw:
            report["clamped_h"].append(f"{xu['ec'] or xu['reg']} {xu['cat']}: {h_w} -> {int(hw)}")
        h_w = min(max(h_w, int(hd)), int(hw))
        dy_w = round_step(dyd + op * 4 * 1.2, 50)
        if dy_w > dyw:
            report["clamped_dy"].append(f"{xu['ec'] or xu['reg']} {xu['cat']}: {dy_w} -> {int(dyw)}")
        dy_w = min(max(dy_w, int(dyd)), int(dyw))

        km_rates = None
        # per-km list rates live only in the HTML array — accept both the original
        # schema (pkw/pkd) and our own generated schema (r.km.fw/d) so reruns are idempotent
        pkw, pkd = lg.get("pkw"), lg.get("pkd")
        if pkw is None and isinstance(lg.get("r"), dict) and isinstance(lg["r"].get("km"), dict):
            pkw, pkd = lg["r"]["km"].get("fw"), lg["r"]["km"].get("d")
        if pkw is not None and pkd is not None:
            km_w = round_step(pkd + (pkw - pkd) * op / (fuel + op), 5)
            km_w = min(max(km_w, int(pkd)), int(pkw))
            km_rates = {"fw": int(pkw), "w": km_w, "d": int(pkd)}

        unit = {
            "id": i,
            "label": lg["label"],  # keep byte-identical for datalist continuity
            "cat": xu["cat"],
            "reg": xu["reg"],
            "ec": xu["ec"],
            "model": lg.get("model") or xu["model"],
            "year": str(xu["year"]),
            "km": 1 if lg.get("km") else 0,
            "fuel": int(round(fuel)),
            "op": int(round(op)),
            "r": {
                "h": {"fw": int(hw), "w": h_w, "d": int(hd)},
                "dy": {"fw": int(dyw), "w": dy_w, "d": int(dyd)},
                "km": km_rates,
            },
        }
        if est:
            unit["est"] = 1
        fleet.append(unit)

    if report["mismatches"]:
        sys.exit("ERROR: positional merge mismatches:\n" + "\n".join(report["mismatches"]))
    return fleet


def js_block(fleet, portable):
    def dump(arr):
        return json.dumps(arr, separators=(",", ":"), ensure_ascii=False).replace("</", "<\\/")
    return (f"{BEGIN_MARK}\n"
            f"const FLEET_MACHINES = {dump(fleet)};\n"
            f"const PORTABLE_EQUIPMENT = {dump(portable)};\n"
            f"{END_MARK}")


def splice(html, block):
    if BEGIN_MARK in html:
        pattern = re.compile(re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK), re.S)
        return pattern.sub(lambda _: block, html, count=1)
    # first run: replace the two original const lines as one region
    pattern = re.compile(
        r"const FLEET_MACHINES = \[.*?\];\s*\n\s*const PORTABLE_EQUIPMENT = \[.*?\];", re.S)
    if not pattern.search(html):
        sys.exit("ERROR: could not locate the data consts to replace in index.html")
    return pattern.sub(lambda _: block, html, count=1)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--xlsx", default="data/Fleet_Rental_Prices_2026.xlsx")
    ap.add_argument("--html", default="index.html")
    ap.add_argument("--write", action="store_true", help="save changes to the HTML file")
    args = ap.parse_args()

    wb = Workbook(args.xlsx)
    html = open(args.html, encoding="utf-8").read()

    excel_units = parse_fleet_pricing(wb)
    eng_by_ec, cat_mean, global_mean = parse_engineering(wb)
    portable = parse_portable(wb)
    legacy = harvest_legacy(html)

    report = {"mismatches": [], "cat_fallback": [], "global_fallback": [],
              "clamped_h": [], "clamped_dy": []}
    fleet = build_fleet(excel_units, legacy, eng_by_ec, cat_mean, global_mean, report)

    block = js_block(fleet, portable)
    new_html = splice(html, block)

    km_units = sum(1 for f in fleet if f["r"]["km"])
    est_units = sum(1 for f in fleet if f.get("est"))
    print(f"Fleet units:      {len(fleet)}  (per-km tiers on {km_units})")
    print(f"Portable items:   {len(portable)}")
    print(f"Engineering join: {len(fleet) - est_units} direct, "
          f"{len(report['cat_fallback'])} category-mean, {len(report['global_fallback'])} global-mean")
    print(f"WET clamped to FULLY WET: hourly {len(report['clamped_h'])}, daily {len(report['clamped_dy'])}")
    if report["cat_fallback"]:
        print("  category-mean units:", ", ".join(report["cat_fallback"][:12]),
              "…" if len(report["cat_fallback"]) > 12 else "")
    if report["global_fallback"]:
        print("  global-mean units:  ", ", ".join(report["global_fallback"][:12]),
              "…" if len(report["global_fallback"]) > 12 else "")
    print(f"HTML size:        {len(html):,} -> {len(new_html):,} bytes")

    if args.write:
        open(args.html, "w", encoding="utf-8").write(new_html)
        print(f"WROTE {args.html}")
    else:
        print("dry run — pass --write to save")


if __name__ == "__main__":
    main()
